### ISSUE TITLE
Re-enable mutli-screen breaks on Windows

### ISSUE THREAD

**Issue by reoxey** [tom-james-watson/breaktimer-app#136]
Currently, the popup is shown only on primary display.
It would be great to have the same popup on multiple connected screens.

**Comment by sanidhya-saraswat** [comment]
which OS are you using ?

**Comment by tom-james-watson** [comment]
It will be windows. On windows this is explicitly disabled because it was not behaving correctly. See:

https://github.com/tom-james-watson/breaktimer-app/blob/bbbacdbec939fce495a6701b69b949fc6465b822/app/main/lib/windows.ts#L88-L93

I'm hoping that this is a bug in Electron and that a future version will fix it.

**Comment by balajikris** [comment]
> I'm hoping that this is a bug in Electron and that a future version will fix it.

FWIW, this used to work in v0.9.0. So, I guess it wasn't disabled in code back then? If this will really be dependent on electron fixing a bug, can we consider adding an option to choose which screen to pop-up on as that gives a simple way out?

p.s: I couldn't go back to 0.9.0 because I'm running this on my employer's devices and I don't have permissions to run unsigned exes. thanks for fixing signing btw!
