### ISSUE TITLE
Option to configure, whether locking the screen on Windows resets the countdown

### ISSUE THREAD

**Issue by Cysioland** [tom-james-watson/breaktimer-app#23]

**Comment by tom-james-watson** [comment]
Looks like in theory theory this is possible with https://electronjs.org/docs/api/power-monitor#event-lock-screen-macos-windows

However, I'm curious as to why you think this is necessary when there's already the idle reset functionality? When you come back to your computer after it having been locked the break will reset due to you having been idle anyway, no?

**Comment by Cysioland** [comment]
On my work computer no matter how long am I away from the desk, it still
resets. I want to disable that.

>

**Comment by tom-james-watson** [comment]
Oh so you're saying that the problem is it always resets and you don't want it to?

Do you have idle reset turned on? If so, what value is it set to? 

If you lock your screen then immediately unlock it, does it reset? If so, turn on the idle reset notification option, and it should tell you in the notification how long you were considered idle. How long does it say?

**Comment by tom-james-watson** [comment]
Will close for now. If we receive more information then we can re-open.
