### ISSUE TITLE
Feature Request: Re-implement 3 minute delay

### ISSUE THREAD

**Issue by dpDesignz** [tom-james-watson/breaktimer-app#6]
Loving the new builds so far (although I had to remove some of the older versions as they weren't uninstalling when new ones came along. I think this is fixed now). One feature I'd love to see implemented is the delay 3 minutes like the browser extension offers. You're doing an awesome job!

**Comment by tom-james-watson** [comment]
Yeah that's likely - I had to change things like the app ID which would break auto-updates. Should work now.

If you go to settings, you can set the "Clicking break start notification should" option to "Postpone the break", which should let you do that.

Unfortunately Electron, the framework the app is built with, does not support buttons on the notifications, so it's not possible to have the separate "Skip" and "Postpone" buttons like the extension did.

The only possible way I can think to get round that problem is to create a popup window that appears when a break is about to start instead of using a notification. That way you could style the popup in any way you want, adding buttons etc. However that then has the problem of not fitting the native UI for notifications, nor the UX of where system notifications should appear etc. I imagine it would also be more buggy in terms of potentially not appearing always on top and things like that.

**Comment by dpDesignz** [comment]
Ah very cool. No that makes sense. I've defaulted my pop-up for skipping as I can just end the break if I want to skip it. You've done an awesome job! Thanks for all the hard work.

**Comment by tom-james-watson** [comment]
Thanks! Will close this out for now. Maybe if lots of people request this then I'll consider the above idea.
