### ISSUE TITLE
BreakTimer Windows app crash on switching to other app

### ISSUE THREAD

**Issue by codeitram** [tom-james-watson/breaktimer-app#97]
So when break timer pops up full screen notification, and if you press alt+tab and change to other app, the screen with notification is gone you can't find it and it crashes on next pop-up scheduled

**Comment by tom-james-watson** [comment]
What version of Windows are you running. I don't see this behaviour on the latest version of Windows 10. I can't actually focus another app whilst the fullscreen break window is shown as the window force renders always on top by design. But regardless, pressing alt+tab does not crash the app for me.

**Comment by codeitram** [comment]
Yup right, I tried it again and I am not able to change focus to other app, but earlier it did happened and crashed, I would try to reproduce it if possible and will SS for same.

**Comment by codeitram** [comment]
Though I totally forget to answer you question, I am on windows 20H2

**Comment by tom-james-watson** [comment]
OK, thanks! It's the kind of thing that probably just needs a bump of electron to fix to be honest. Unlikely to be something in breaktimer itself.
